PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZPL_ORDER_CONV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZPL_ORDER_CONV-COMP_CODE .
    FIELD ZPL_ORDER_CONV-COORD_TYPE .
    FIELD ZPL_ORDER_CONV-ZMAR .
    FIELD ZPL_ORDER_CONV-GL_ACCOUNT .
    FIELD ZPL_ORDER_CONV-COORDER .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZPL_ORDER_CONV-COMP_CODE .
    FIELD ZPL_ORDER_CONV-COORD_TYPE .
    FIELD ZPL_ORDER_CONV-ZMAR .
    FIELD ZPL_ORDER_CONV-GL_ACCOUNT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
